#
# Module manifest for module 'MyProfileUtils'
#
# Generated by: krawlz
#

@{
    RootModule        = 'MyProfileUtils.psm1'
    ModuleVersion     = '1.0'
    GUID              = '886ad269-9b41-4d0d-83d7-589bb71368f'
    Author            = 'krawlz'
    CompanyName       = 'Unknown'
    Copyright         = '(c) 2026 krawlz. All rights reserved.'
    Description       = 'Utility functions for PowerShell Profile'

    FunctionsToExport = @(
        # Git
        'gc', 'gca', 'gp', 'gpu', 'gst', 'glog', 'gdiff', 'gco', 'gb', 'gba',
        'gadd', 'ga', 'gcoall', 'gr', 'gre',
        # Docker
        'dco', 'dps', 'dpa', 'dl', 'dx',
        # Navigation
        'cd..', 'cd...', 'cd....', 'cd.....', 'cd......', 'cx',
        # Kubernetes
        'k', 'ka', 'kg', 'kd', 'kdel', 'kl', 'ke', 'kgpo', 'kgd', 'kc', 'kns', 'kcns',
        # Listing
        'l', 'lt', 'ltree',
        # Security
        'gobust', 'dirsearch', 'massdns', 'server', 'tunnel', 'fuzz',
        # FZF navigation
        'fcd', 'f', 'fv',
        # Misc
        'rr', 'j'
    )

    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'

    PrivateData = @{
        PSData = @{}
    }
}
